# Generated by Django 3.1a1 on 2020-05-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='애플 아뒤'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_paid',
            field=models.BooleanField(default=False, verbose_name='💳결제'),
        ),
    ]
