# Generated by Django 3.0.5 on 2020-04-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='has_paid',
        ),
        migrations.AddField(
            model_name='user',
            name='has_submited_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_submited_survey',
            field=models.BooleanField(default=False),
        ),
    ]
