# Generated by Django 3.0.5 on 2020-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_has_habit_check_list_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_submited_survey',
            field=models.BooleanField(default=False),
        ),
    ]
