# Generated by Django 3.0.5 on 2020-04-23 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200420_1100'),
        ('users', '0002_user_has_kakao_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.ClassOrder'),
        ),
    ]
