# Generated by Django 3.0.5 on 2020-04-23 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20200424_0858'),
        ('users', '0003_user_class_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.ClassOrder'),
        ),
    ]
