# Generated by Django 3.0.5 on 2020-05-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_has_submited_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_habit_check_list_submitted',
            new_name='has_apple_account',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='has_later_check_list_submitted',
            new_name='has_submitted_application',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='has_previous_check_list_submitted',
            new_name='has_submitted_habit_check_list',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='has_submited_application',
            new_name='has_submitted_later_check_list',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='has_submited_survey',
            new_name='has_submitted_previous_check_list',
        ),
        migrations.AddField(
            model_name='user',
            name='has_submitted_survey',
            field=models.BooleanField(default=False),
        ),
    ]
