# Generated by Django 3.0.5 on 2020-05-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_childbirth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_childbirth_etc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_married',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_married_etc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='how_many_child',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
