# Generated by Django 3.0.5 on 2020-05-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200527_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='how_many_child',
        ),
    ]
