# Generated by Django 3.0.5 on 2020-05-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_how_many_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appleId',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
