# Generated by Django 3.1a1 on 2020-05-31 05:09

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20200531_1409'),
        ('users', '0009_auto_20200529_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_kakao_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kakao_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_img',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='애플 아뒤'),
        ),
        migrations.AlterField(
            model_name='user',
            name='approach',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('APPROACH_A', '지인 소개'), ('APPROACH_B', '카페, 블로그'), ('APPROACH_C', '페이스북, 트위터'), ('APPROACH_D', '책 <치유본능>'), ('APPROACH_E', '책 <짠맛의 힘>'), ('APPROACH_F', '홈페이지(자하누리, 직관의 몸공부)')], max_length=65, null=True, verbose_name='경로'),
        ),
        migrations.AlterField(
            model_name='user',
            name='approach_etc',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='경로 기타'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='class_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.classorder', verbose_name='기수'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('GENDER_MALE', '남성'), ('GENDER_FEMALE', '여성'), ('GENDER_OTHER', 'Other')], max_length=20, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_apple_account',
            field=models.BooleanField(default=False, verbose_name='애플 로긴'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_childbirth',
            field=models.BooleanField(default=False, verbose_name='출산'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_childbirth_etc',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='출산 기타'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_married',
            field=models.BooleanField(default=False, verbose_name='결혼'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_married_etc',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='결혼 기타'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_paid',
            field=models.BooleanField(default=False, verbose_name='결제'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_submitted_application',
            field=models.BooleanField(default=False, verbose_name='신청서'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_submitted_habit_check_list',
            field=models.BooleanField(default=False, verbose_name='습관'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_submitted_later_check_list',
            field=models.BooleanField(default=False, verbose_name='체크 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_submitted_previous_check_list',
            field=models.BooleanField(default=False, verbose_name='체크 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_submitted_survey',
            field=models.BooleanField(default=False, verbose_name='설문지'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='직업'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='폰번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='고유 번호'),
        ),
    ]
