# Generated by Django 3.0.5 on 2020-05-26 04:03

from django.db import migrations, models
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, choices=[('GENDER_MALE', 'Male'), ('GENDER_FEMALE', 'Female'), ('GENDER_OTHER', 'Other')], max_length=20, null=True)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=2000)),
                ('job', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('email_address', models.CharField(max_length=500)),
                ('approach', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('APPROACH_A', '지인 소개'), ('APPROACH_B', '카페, 블로그'), ('APPROACH_C', '페이스북, 트위터'), ('APPROACH_D', '책 <치유본능>'), ('APPROACH_E', '책 <짠맛의 힘>'), ('APPROACH_F', '홈페이지(자하누리, 직관의 몸공부)')], max_length=65, null=True)),
                ('approach_etc', models.CharField(blank=True, max_length=2000, null=True)),
                ('confirm', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, null=True, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('saeng_sik_morning', models.CharField(blank=True, max_length=200, null=True)),
                ('saeng_sik_noon', models.CharField(blank=True, max_length=200, null=True)),
                ('saeng_sik_evening', models.CharField(blank=True, max_length=200, null=True)),
                ('amino_morning', models.CharField(blank=True, max_length=200, null=True)),
                ('amino_noon', models.CharField(blank=True, max_length=200, null=True)),
                ('amino_evening', models.CharField(blank=True, max_length=200, null=True)),
                ('sangi_so_morning', models.CharField(blank=True, max_length=200, null=True)),
                ('sangi_so_noon', models.CharField(blank=True, max_length=200, null=True)),
                ('sangi_so_evening', models.CharField(blank=True, max_length=200, null=True)),
                ('jeun_hae_jil_a', models.BooleanField(default=False)),
                ('jeun_hae_jil_b', models.BooleanField(default=False)),
                ('jeun_hae_jil_c', models.BooleanField(default=False)),
                ('jeun_hae_jil_d', models.BooleanField(default=False)),
                ('meal', models.CharField(max_length=1000)),
                ('meal_check', models.CharField(max_length=1000)),
                ('sleeping', models.CharField(max_length=1000)),
                ('stool', models.CharField(max_length=1000)),
                ('hot_grain', models.CharField(max_length=1000)),
                ('hot_water', models.CharField(max_length=1000)),
                ('strolling', models.CharField(max_length=1000)),
                ('workout', models.CharField(max_length=1000)),
                ('lecture', models.CharField(max_length=1000)),
                ('etc', models.CharField(max_length=1000)),
                ('diary', models.CharField(max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_type', models.CharField(choices=[('body study', 'Body Study'), ('etc', 'Etc')], default='body study', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_married', models.BooleanField(default=False)),
                ('has_married_etc', models.CharField(blank=True, max_length=2000, null=True)),
                ('has_childbirth', models.BooleanField(default=False)),
                ('has_childbirth_etc', models.CharField(blank=True, max_length=2000, null=True)),
                ('how_many_child', models.CharField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(blank=True, max_length=2000, null=True)),
                ('change', models.CharField(blank=True, max_length=2000, null=True)),
                ('agree_personal_information', models.BooleanField(default=False)),
                ('confirm', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
