# Generated by Django 3.1a1 on 2020-05-31 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AddField(
            model_name='reportcover',
            name='class_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_order_set', to='classes.classorder', verbose_name='기수'),
        ),
        migrations.AddField(
            model_name='reportcover',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_set', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.reportcover', verbose_name='일지 커버'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
    ]
