# Generated by Django 3.0.5 on 2020-05-24 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0002_auto_20200524_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_married', models.BooleanField(default=False)),
                ('has_married_etc', models.CharField(blank=True, max_length=2000, null=True)),
                ('has_childbirth', models.BooleanField(default=False)),
                ('has_childbirth_etc', models.CharField(blank=True, max_length=2000, null=True)),
                ('how_many_child', models.CharField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(blank=True, max_length=2000, null=True)),
                ('change', models.CharField(blank=True, max_length=2000, null=True)),
                ('agree_personal_information', models.BooleanField(default=False)),
                ('confirm', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('GENDER_MALE', 'Male'), ('GENDER_FEMALE', 'Female'), ('GENDER_OTHER', 'Other')], max_length=20, null=True)),
                ('job', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
