# Generated by Django 3.0.5 on 2020-05-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200428_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='jeun_hae_jil_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
