# Generated by Django 3.0.5 on 2020-05-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200526_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
