# Generated by Django 3.0.5 on 2020-04-23 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200420_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='sang_sik',
            new_name='saeng_sik',
        ),
        migrations.AlterField(
            model_name='classorder',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reportcover',
            name='class_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.ClassOrder'),
        ),
        migrations.AlterField(
            model_name='reportcover',
            name='report_type',
            field=models.CharField(choices=[('body study', 'Body Study'), ('etc', 'Etc')], default='body study', max_length=200),
        ),
    ]
