# Generated by Django 3.0.5 on 2020-05-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20200518_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='amino_evening',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='amino_morning',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='amino_noon',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='saeng_sik_evening',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='saeng_sik_noon',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='sangi_so_evening',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='sangi_so_morning',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='sangi_so_noon',
            field=models.CharField(max_length=200),
        ),
    ]
