# Generated by Django 3.0.5 on 2020-05-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20200518_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='saeng_sik_morning',
            field=models.CharField(max_length=200),
        ),
    ]
