# Generated by Django 3.1a1 on 2020-05-31 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0005_remove_survey_how_many_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.CharField(max_length=2000, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='application',
            name='approach',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('APPROACH_A', '지인 소개'), ('APPROACH_B', '카페, 블로그'), ('APPROACH_C', '페이스북, 트위터'), ('APPROACH_D', '책 <치유본능>'), ('APPROACH_E', '책 <짠맛의 힘>'), ('APPROACH_F', '홈페이지(자하누리, 직관의 몸공부)')], max_length=65, null=True, verbose_name='경로'),
        ),
        migrations.AlterField(
            model_name='application',
            name='approach_etc',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='경로 기타'),
        ),
        migrations.AlterField(
            model_name='application',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='application',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='확인'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email_address',
            field=models.CharField(max_length=500, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(blank=True, choices=[('GENDER_MALE', '남성'), ('GENDER_FEMALE', '여성'), ('GENDER_OTHER', 'Other')], max_length=20, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.CharField(max_length=500, verbose_name='직업'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=500, verbose_name='폰번호'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AlterField(
            model_name='classorder',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='끝일'),
        ),
        migrations.AlterField(
            model_name='classorder',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='기수'),
        ),
        migrations.AlterField(
            model_name='classorder',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='classorder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='고유 번호'),
        ),
        migrations.AlterField(
            model_name='report',
            name='amino_evening',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='아미노 저녁'),
        ),
        migrations.AlterField(
            model_name='report',
            name='amino_morning',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='아미노 아침'),
        ),
        migrations.AlterField(
            model_name='report',
            name='amino_noon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='아미노 점심'),
        ),
        migrations.AlterField(
            model_name='report',
            name='diary',
            field=models.CharField(max_length=5000, verbose_name='세줄 일기'),
        ),
        migrations.AlterField(
            model_name='report',
            name='etc',
            field=models.CharField(max_length=1000, verbose_name='기타'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hot_grain',
            field=models.CharField(max_length=1000, verbose_name='곡식 찜질'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hot_water',
            field=models.CharField(max_length=1000, verbose_name='따뜻한 물'),
        ),
        migrations.AlterField(
            model_name='report',
            name='jeun_hae_jil_a',
            field=models.BooleanField(default=False, verbose_name='전해질 1'),
        ),
        migrations.AlterField(
            model_name='report',
            name='jeun_hae_jil_b',
            field=models.BooleanField(default=False, verbose_name='전해질 2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='jeun_hae_jil_c',
            field=models.BooleanField(default=False, verbose_name='전해질 3'),
        ),
        migrations.AlterField(
            model_name='report',
            name='jeun_hae_jil_d',
            field=models.BooleanField(default=False, verbose_name='전해질 4'),
        ),
        migrations.AlterField(
            model_name='report',
            name='lecture',
            field=models.CharField(max_length=1000, verbose_name='강의'),
        ),
        migrations.AlterField(
            model_name='report',
            name='meal',
            field=models.CharField(max_length=1000, verbose_name='일반 식사'),
        ),
        migrations.AlterField(
            model_name='report',
            name='meal_check',
            field=models.CharField(max_length=1000, verbose_name='식사 습관 체크'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.reportcover', verbose_name='일지 커버'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(verbose_name='일지 날짜'),
        ),
        migrations.AlterField(
            model_name='report',
            name='saeng_sik_evening',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='섭생식 저녁'),
        ),
        migrations.AlterField(
            model_name='report',
            name='saeng_sik_morning',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='섭생식 아침'),
        ),
        migrations.AlterField(
            model_name='report',
            name='saeng_sik_noon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='섭생식 점심'),
        ),
        migrations.AlterField(
            model_name='report',
            name='sangi_so_evening',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='생기소 저녁'),
        ),
        migrations.AlterField(
            model_name='report',
            name='sangi_so_morning',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='생기소 아침'),
        ),
        migrations.AlterField(
            model_name='report',
            name='sangi_so_noon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='생기소 점심'),
        ),
        migrations.AlterField(
            model_name='report',
            name='sleeping',
            field=models.CharField(max_length=1000, verbose_name='잠'),
        ),
        migrations.AlterField(
            model_name='report',
            name='stool',
            field=models.CharField(max_length=1000, verbose_name='변'),
        ),
        migrations.AlterField(
            model_name='report',
            name='strolling',
            field=models.CharField(max_length=1000, verbose_name='걷기'),
        ),
        migrations.AlterField(
            model_name='report',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='고유 번호'),
        ),
        migrations.AlterField(
            model_name='report',
            name='workout',
            field=models.CharField(max_length=1000, verbose_name='운동'),
        ),
        migrations.AlterField(
            model_name='reportcover',
            name='class_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_order_set', to='classes.classorder', verbose_name='기수'),
        ),
        migrations.AlterField(
            model_name='reportcover',
            name='report_type',
            field=models.CharField(choices=[('BODY_STUDY', '몸공부'), ('ETC', '기타')], default='BODY_STUDY', max_length=200, verbose_name='일지 타입'),
        ),
        migrations.AlterField(
            model_name='reportcover',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_set', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AlterField(
            model_name='reportcover',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='고유 번호'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='agree_personal_information',
            field=models.BooleanField(default=False, verbose_name='개인정보 동의'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='change',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='변화'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='확인'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='has_childbirth',
            field=models.BooleanField(default=False, verbose_name='출산'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='has_childbirth_etc',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='출산 기타'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='has_married',
            field=models.BooleanField(default=False, verbose_name='결혼'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='has_married_etc',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='결혼 기타'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
    ]
