# Generated by Django 3.0.5 on 2020-05-20 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20200519_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='classorder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
