# Generated by Django 3.0.5 on 2020-05-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_classorder_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcover',
            name='class_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_order_set', to='classes.ClassOrder'),
        ),
    ]
