# Generated by Django 3.0.5 on 2020-05-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20200520_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='jeun_hae_jil',
            new_name='jeun_hae_jil_a',
        ),
        migrations.AddField(
            model_name='report',
            name='jeun_hae_jil_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='jeun_hae_jil_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='jeun_hae_jil_d',
            field=models.BooleanField(default=False),
        ),
    ]
