# Generated by Django 3.1a1 on 2020-05-31 17:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='만들어진 날')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트된 날')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='고유 번호')),
                ('text', models.TextField(blank=True, null=True, verbose_name='공지')),
                ('class_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.classorder', verbose_name='기수')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
