# Generated by Django 3.1a1 on 2020-05-31 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20200531_1409'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0003_auto_20200527_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='class_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.classorder', verbose_name='기수'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='공지'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='고유 번호'),
        ),
    ]
