# Generated by Django 3.1a1 on 2020-05-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20200531_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='만들어진 날'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='업데이트된 날'),
        ),
    ]
