# Generated by Django 3.0.5 on 2020-04-20 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodyClasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcover',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='report_cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodyClasses.ReportCover'),
        ),
    ]
