# Generated by Django 3.0.5 on 2020-04-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodyClasses', '0002_auto_20200420_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcover',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportcover',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
