# Generated by Django 3.0.5 on 2020-04-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodyClasses', '0003_auto_20200420_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcover',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
