from django.core.management.base import BaseCommand
from checklists.models import CheckListQuestion


NAME = "check list"


class Command(BaseCommand):

    help = f"This commend creates {NAME}"

    def handle(self, *args, **options):
        questions = [
            {"question": "눈이시고눈물이난다", "element": "wood"},
            {"question": "안구가 건조하다", "element": "wood"},
            {"question": "편두통이 있다", "element": "wood"},
            {"question": "피부가 건조하고 가려움증이 있다 ", "element": "wood"},
            {"question": "목이잘쉬고가래가낀다 ", "element": "wood"},
            {"question": "옆구리가결리고다리에쥐가잘난다 ", "element": "wood"},
            {"question": "불면증,수면장애 ", "element": "wood"},
            {"question": "목감기가잘오고편도선에이상이있다 ", "element": "wood"},
            {"question": "구역질이잘나고소화가잘안된다", "element": "wood"},
            {"question": "밥맛이없고면,빵등밀가루음식을찾는다", "element": "wood"},
            {"question": "다리가 안으로 혹은 밖으로 휘어 있다", "element": "wood"},
            {"question": "고관절이안좋다 ", "element": "wood"},
            {"question": "발이잘피곤하다 ", "element": "wood"},
            {"question": "걸음이 빠르고 성격이 급하다", "element": "wood"},
            {"question": "쉬지 못하고 계속 무언가를 한다", "element": "wood"},
            {"question": "못마땅하고 거슬리는 것이 많다", "element": "wood"},
            {"question": "가슴이 답답하고 한숨을 잘 쉰다", "element": "wood"},
            {"question": "나도모르게욱하고화가난다 ", "element": "wood"},
            {"question": "딸꾹질을 잘 한다", "element": "fire"},
            {"question": "눈에다래끼가잘나거나충혈이잘된다", "element": "fire"},
            {"question": "깜짝깜짝 놀란다", "element": "fire"},
            {"question": "윗팔뚝이 굵거나 닭살이 있다 ", "element": "fire"},
            {"question": "팔꿈치나 날갯죽지가 잘 아프다 ", "element": "fire"},
            {"question": "얼굴이붉은편이고특히볼이잘빨개진다 ", "element": "fire"},
            {"question": "광대뼈주변에기미주근깨가있다 ", "element": "fire"},
            {"question": "새끼 손가락에 이상이 있다 (짧거나 꼬부라짐) ", "element": "fire"},
            {"question": "혓바늘이잘돋거나혀가갈라지는등혀에이상 ", "element": "fire"},
            {"question": "가슴이두근거린다 ", "element": "fire"},
            {"question": "조금만걸어도숨이찬다 ", "element": "fire"},
            {"question": "부탁을하면거절을잘못한다", "element": "fire"},
            {"question": "먼저말걸어오기전에는인사를잘안한다", "element": "fire"},
            {"question": "웃고싶지않은데웃음이난다", "element": "fire"},
            {"question": "말끝을 흐린다", "element": "fire"},
            {"question": "말을 더듬는다", "element": "fire"},
            {"question": "꿈을많이꾼다", "element": "fire"},
            {"question": "화병이 있다", "element": "fire"},
            {"question": "입맛이 까다롭지 않고 식사량이 많다 ", "element": "earth"},
            {"question": "얼굴이 누르끼리하고 개기름이 낀다 ", "element": "earth"},
            {"question": "무릎이시큰거리고앉았다일어날때빨리펴지못한다 ", "element": "earth"},
            {"question": "물을많이마시고특히찬물을좋아한다 ", "element": "earth"},
            {"question": "눈꺼풀이 떨리거나 손이 떨린다 ", "element": "earth"},
            {"question": "눈밑이불룩하게나와있다 ", "element": "earth"},
            {"question": "입술이잘부르트고입병이잘난다 ", "element": "earth"},
            {"question": "윗배가 나오고 전반적으로 군살이 많다 ", "element": "earth"},
            {"question": "피부에멍이잘든다 ", "element": "earth"},
            {"question": "누워있기 좋아 한다", "element": "earth"},
            {"question": "달콤한 것을 좋아하지만 살이 찔까봐 마음껏 못 먹는다", "element": "earth"},
            {"question": "생각이 많다", "element": "earth"},
            {"question": "의심을 많이 한다", "element": "earth"},
            {"question": "같은 얘기를 반복하거나 같은 노래를 계속 흥얼거린다", "element": "earth"},
            {"question": "계획만 세우고 실천을 잘 못한다", "element": "earth"},
            {"question": "약속시간을잘못지킨다", "element": "earth"},
            {"question": "게을러지고 일을 미룬다", "element": "earth"},
            {"question": "걱정이 많다", "element": "earth"},
            {"question": "콧물, 재채기가 잘 난다", "element": "metal"},
            {"question": "피부가 탄력이 없고 늘어져 있다", "element": "metal"},
            {"question": "얼굴이 허옇고 창백하다", "element": "metal"},
            {"question": "치질, 치루가 있다", "element": "metal"},
            {"question": "숨이 차다", "element": "metal"},
            {"question": "코가막히고냄새를잘못맡는다", "element": "metal"},
            {"question": "손목이 약하고 아귀힘이 없다", "element": "metal"},
            {"question": "엄지손가락이 자주 아프다", "element": "metal"},
            {"question": "건조한 것을 싫어한다", "element": "metal"},
            {"question": "허리 아래가 빠지듯 아프다", "element": "metal"},
            {"question": "등이 굽고 아랫배를 내미는 자세로 걷는다", "element": "metal"},
            {"question": "설사를 잘하고 변이 묽다", "element": "metal"},
            {"question": "매운 것을 좋아한다", "element": "metal"},
            {"question": "남을 불쌍하게 여기고 동정심이 지나치다", "element": "metal"},
            {"question": "의욕이 없고 공허함을 잘 느낀다", "element": "metal"},
            {"question": "염세적이다", "element": "metal"},
            {"question": "죽고싶은마음이잘든다", "element": "metal"},
            {"question": "눈물이 많다", "element": "metal"},
            {"question": "뒷골이 당기고, 뒷목이 뻐근하다", "element": "water"},
            {"question": "눈알이뻑뻑하고빠질것같다", "element": "water"},
            {"question": "귀에 이상(청력이 떨어진다, 귀에서 소리, 가려움증, 중이염,)", "element": "water"},
            {"question": "얼굴빛이 윤기가 없고 거무튀튀", "element": "water"},
            {"question": "허리나 등이 아프다", "element": "water"},
            {"question": "발목을 잘 접지른다", "element": "water"},
            {"question": "발바닥이 뜨겁거나 아프다", "element": "water"},
            {"question": "몸이나 종아리가 잘 붓는다", "element": "water"},
            {"question": "몸여러곳에염증이있다 ", "element": "water"},
            {"question": "하품을잘한다 ", "element": "water"},
            {"question": "소변을자주본다 ", "element": "water"},
            {"question": "허리가약하고자주삐끗,디스크,요통 ", "element": "water"},
            {"question": "뼈가약하거나치아가좋지않다 ", "element": "water"},
            {"question": "탈모가있거나머릿결이좋지않다 ", "element": "water"},
            {"question": "전립선, 자궁, 생식기 이상 ", "element": "water"},
            {"question": "추위를많이탄다 ", "element": "water"},
            {"question": "지구력이 부족해서 꾸준히 하지 못한다 ", "element": "water"},
            {"question": "부정적인편이고반대를잘한다 ", "element": "water"},
            {"question": "늘피곤하고쉽게지친다 ", "element": "water"},
            {"question": "열이올랐다내렸다한다 ", "element": "sanghwa"},
            {"question": "어깨가무겁고결린다 ", "element": "sanghwa"},
            {"question": "목에뭐가걸린것같고잔기침,헛기침을잘한다 ", "element": "sanghwa"},
            {"question": "음식물을잘못넘기고사래에잘걸린다 ", "element": "sanghwa"},
            {"question": "잘 체하고 명치끝이 답답하다 ", "element": "sanghwa"},
            {"question": "미간이 찌푸려지고 표정이 다양하지 않다 ", "element": "sanghwa"},
            {"question": "나도모르게인상을쓰고있다 ", "element": "sanghwa"},
            {"question": "환절기에몸이힘들고감기나몸살을한다 ", "element": "sanghwa"},
            {"question": "손가락 마디가 굵어지고 손저린증, 손에허물벗겨지는등손에이상", "element": "sanghwa"},
            {"question": "다한증,손이차고땀이많이난다 ", "element": "sanghwa"},
            {"question": "운동신경, 특히 순발력이 떨어진다 ", "element": "sanghwa"},
            {"question": "꼬리뼈가아프다 ", "element": "sanghwa"},
            {"question": "틱증상이있다 ", "element": "sanghwa"},
            {"question": "신경이예민하다 ", "element": "sanghwa"},
            {"question": "감정기복이심하다 ", "element": "sanghwa"},
            {"question": "불안초조 ", "element": "sanghwa"},
            {"question": "우울증이 있고 사람 만나는 것이 싫어진다", "element": "sanghwa"},
            {"question": "아니꼽고 치사한 일이 많다", "element": "sanghwa"},
        ]

        for i in questions:
            CheckListQuestion.objects.create(
                question=i["question"], element=i["element"]
            )
        self.stdout.write(self.style.SUCCESS(f"{len(questions)} {NAME} created"))
