# Generated by Django 3.1b1 on 2020-07-09 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habitchecklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_checklist_user', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AddField(
            model_name='checklistanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='checklists.checklistquestion', verbose_name='질문'),
        ),
        migrations.AddField(
            model_name='checklistanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkListAnswers', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
    ]
