# Generated by Django 3.0.5 on 2020-05-24 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklists', '0002_auto_20200524_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitchecklist',
            name='after_lunch',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('스마트폰을 본다', '스마트폰을 본다'), ('밖에 나가 걷거나 산책을 한다', '밖에 나가 걷거나 산책을 한다'), ('담배를 핀다', '담배를 핀다'), ('커피 등 후식을 즐긴다', '커피 등 후식을 즐긴다'), ('잠이 쏟아진다', '수다를 즐긴다'), ('잠이 쏟아진다', '잠이 쏟아진다')], default=1, max_length=61),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='after_lunch_etc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='meal',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='meal_during',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('대화를 많이 하는 편이다', '대화를 많이 하는 편이다'), ('먹는 것에 집중하는 편이다', '먹는 것에 집중하는 편이다'), ('TV, 스마트폰 등을 보면서 먹는다', 'TV, 스마트폰 등을 보면서 먹는다'), ('꼭꼭 씹어서 먹는다', '꼭꼭 씹어서 먹는다'), ('급하게 먹는다', '급하게 먹는다'), ('많이 먹는다', '많이 먹는다'), ('입이 짧다 (많이 못 먹는다)', '입이 짧다 (많이 못 먹는다)'), ('음식의 맛을 음미하면서 먹는다', '음식의 맛을 음미하면서 먹는다'), ('끼니 때우듯 먹는 편이다', '끼니 때우듯 먹는 편이다'), ('식욕이 별로 없다', '식욕이 별로 없다'), ('밥맛이 아주 좋다', '밥맛이 아주 좋다')], default=1, max_length=142),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='meal_during_etc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='meal_with_night_food',
            field=models.CharField(choices=[('안한다', '안한다'), ('거의 안한다', '거의 안한다'), ('가끔 한다', '가끔 한다'), ('거의 한다', '거의 한다'), ('자주 한다', '자주 한다')], default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='meal_with_snack',
            field=models.CharField(choices=[('안한다', '안한다'), ('거의 안한다', '거의 안한다'), ('가끔 한다', '가끔 한다'), ('거의 한다', '거의 한다'), ('자주 한다', '자주 한다')], default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='meal_with_water',
            field=models.CharField(choices=[('안한다', '안한다'), ('거의 안한다', '거의 안한다'), ('가끔 한다', '가끔 한다'), ('거의 한다', '거의 한다'), ('자주 한다', '자주 한다')], default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='saying',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('말의 속도가 빠르다', '말의 속도가 빠르다'), ('듣는 것보다 말하는 것에 더 익숙하다', '듣는 것보다 말하는 것에 더 익숙하다'), ('상대방의 말을 잘 듣는 편이다', '상대방의 말을 잘 듣는 편이다'), ('말을 자주 더듬는다', '말을 자주 더듬는다'), ('말을 거침없이 한다', '말을 거침없이 한다'), ('자주 흥분해서 말한다', '자주 흥분해서 말한다'), ('말이 별로 없다', '말이 별로 없다'), ('생각을 하고 말을 하는 편이다', '생각을 하고 말을 하는 편이다'), ('말을 하면서 생각하는 편이다', '말을 하면서 생각하는 편이다'), ('말실수를 많이 한다', '말실수를 많이 한다'), ('부정적인 반응을 자주 보인다(아닌 것 같은데~ 등)', '부정적인 반응을 자주 보인다(아닌 것 같은데~ 등)')], default=1, max_length=164),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='saying_etc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='wakeup_condition_etc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='wakeup_first_thing',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('개운하다', '찬물 혹은 찬음료를 마신다'), ('머리가 아프다', '뜨거운 물 혹은 차를 마신다'), ('눈이 아프거나 잘 안 떠진다', '가벼운 스트레칭'), ('몸이 결리거나 뻐근하다', '양치, 세수, 샤워'), ('일어나기 힘들다', '스마트폰'), ('멍하다', '잡지, 신문')], default=11, max_length=54),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='wakeup_first_thing_etc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='job',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='wakeup_condition',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('개운하다', '개운하다'), ('머리가 아프다', '머리가 아프다'), ('눈이 아프거나 잘 안 떠진다', '눈이 아프거나 잘 안 떠진다'), ('몸이 결리거나 뻐근하다', '몸이 결리거나 뻐근하다'), ('일어나기 힘들다', '일어나기 힘들다'), ('멍하다', '멍하다'), ('손이나 발 등이 저리다', '손이나 발 등이 저리다'), ('부어있다 (얼굴, 손, 발 등)', '부어있다 (얼굴, 손, 발 등)')], max_length=85),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='wakeup_long',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='wakeup_time',
            field=models.CharField(max_length=200),
        ),
    ]
