# Generated by Django 3.0.5 on 2020-05-24 11:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_auto_20200524_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitchecklist',
            name='body_heat',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('열이 많아서 옷을 얇게 입는다', '열이 많아서 옷을 얇게 입는다'), ('찬물을 피한다', '찬물을 피한다'), ('찬물을 즐겨 마신다', '찬물을 즐겨 마신다'), ('뜨거운 차를 자주 마신다', '뜨거운 차를 자주 마신다'), ('핫팩을 자주 붙이고 다닌다', '핫팩을 자주 붙이고 다닌다'), ('목도리, 장갑 등을 챙겨서 한다', '목도리, 장갑 등을 챙겨서 한다'), ('내의를 챙겨 입는다', '내의를 챙겨 입는다'), ('발을 항상 따듯하게 해 준다', '발을 항상 따듯하게 해 준다'), ('발이 답답해서 집에서 맨발로 다닌다', '발이 답답해서 집에서 맨발로 다닌다'), ('찜질팩, 돌뜸 등을 늘 챙겨서 한다', '찜질팩, 돌뜸 등을 늘 챙겨서 한다'), ('족탕, 반신욕, 찜질 등을 한다', '족탕, 반신욕, 찜질 등을 한다')], max_length=167, null=True),
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='body_heat_etc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='exercise',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='posture',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('앉아 있는 시간', '앉아 있는 시간'), ('서 있는 시간', '서 있는 시간'), ('걷는 시간', '걷는 시간'), ('교통수단을 이용하는 시간', '교통수단을 이용하는 시간'), ('누워 있는 시간', '누워 있는 시간')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='posture_detail',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('자세를 편하게 잘 펴고 있다', '자세를 편하게 잘 펴고 있다'), ('자세가 무너져 있다', '자세가 무너져 있다'), ('앉아 있는 것에 익숙하다', '앉아 있는 것에 익숙하다'), ('오래 서 있지 못한다', '오래 서 있지 못한다'), ('앉아 있는 게 힘들다', '앉아 있는 게 힘들다'), ('등이 굽어 있거나 거북목이다', '등이 굽어 있거나 거북목이다'), ('일자목, 목이 돌아가지 않는다', '일자목, 목이 돌아가지 않는다'), ('다리를 자주 꼰다', '다리를 자주 꼰다'), ('무지외반증이 있다', '무지외반증이 있다'), ('다리가 휘어 있다 (안으로, 밖으로 등)', '다리가 휘어 있다 (안으로, 밖으로 등)')], max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='posture_detail_etc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='posture_etc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='saying_repeat',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='walking',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('걸음이 느리다', '걸음이 느리다'), ('걸음이 빠른 편이다', '걸음이 빠른 편이다'), ('옆사람과 나란히 걷는다', '옆사람과 나란히 걷는다'), ('앞서서 걷는 편이다', '앞서서 걷는 편이다'), ('발을 끌면서 걷는다', '발을 끌면서 걷는다'), ('허리가 굽어 있다', '허리가 굽어 있다'), ('파워워킹을 한다', '파워워킹을 한다'), ('오래 걷지 못한다', '오래 걷지 못한다')], max_length=82, null=True),
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='walking_etc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='after_lunch',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('스마트폰을 본다', '스마트폰을 본다'), ('밖에 나가 걷거나 산책을 한다', '밖에 나가 걷거나 산책을 한다'), ('담배를 핀다', '담배를 핀다'), ('커피 등 후식을 즐긴다', '커피 등 후식을 즐긴다'), ('수다를 즐긴다', '수다를 즐긴다'), ('잠이 쏟아진다', '잠이 쏟아진다')], max_length=61, null=True),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='meal_during',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('대화를 많이 하는 편이다', '대화를 많이 하는 편이다'), ('먹는 것에 집중하는 편이다', '먹는 것에 집중하는 편이다'), ('TV, 스마트폰 등을 보면서 먹는다', 'TV, 스마트폰 등을 보면서 먹는다'), ('꼭꼭 씹어서 먹는다', '꼭꼭 씹어서 먹는다'), ('급하게 먹는다', '급하게 먹는다'), ('많이 먹는다', '많이 먹는다'), ('입이 짧다 (많이 못 먹는다)', '입이 짧다 (많이 못 먹는다)'), ('음식의 맛을 음미하면서 먹는다', '음식의 맛을 음미하면서 먹는다'), ('끼니 때우듯 먹는 편이다', '끼니 때우듯 먹는 편이다'), ('식욕이 별로 없다', '식욕이 별로 없다'), ('밥맛이 아주 좋다', '밥맛이 아주 좋다')], max_length=142, null=True),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='meal_with_night_food',
            field=models.CharField(blank=True, choices=[('안한다', '안한다'), ('거의 안한다', '거의 안한다'), ('가끔 한다', '가끔 한다'), ('거의 한다', '거의 한다'), ('자주 한다', '자주 한다')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='meal_with_snack',
            field=models.CharField(blank=True, choices=[('안한다', '안한다'), ('거의 안한다', '거의 안한다'), ('가끔 한다', '가끔 한다'), ('거의 한다', '거의 한다'), ('자주 한다', '자주 한다')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='meal_with_water',
            field=models.CharField(blank=True, choices=[('안한다', '안한다'), ('거의 안한다', '거의 안한다'), ('가끔 한다', '가끔 한다'), ('거의 한다', '거의 한다'), ('자주 한다', '자주 한다')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='saying',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('말의 속도가 빠르다', '말의 속도가 빠르다'), ('듣는 것보다 말하는 것에 더 익숙하다', '듣는 것보다 말하는 것에 더 익숙하다'), ('상대방의 말을 잘 듣는 편이다', '상대방의 말을 잘 듣는 편이다'), ('말을 자주 더듬는다', '말을 자주 더듬는다'), ('말을 거침없이 한다', '말을 거침없이 한다'), ('자주 흥분해서 말한다', '자주 흥분해서 말한다'), ('말이 별로 없다', '말이 별로 없다'), ('생각을 하고 말을 하는 편이다', '생각을 하고 말을 하는 편이다'), ('말을 하면서 생각하는 편이다', '말을 하면서 생각하는 편이다'), ('말실수를 많이 한다', '말실수를 많이 한다'), ('부정적인 반응을 자주 보인다(아닌 것 같은데~ 등)', '부정적인 반응을 자주 보인다(아닌 것 같은데~ 등)')], max_length=164, null=True),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='wakeup_condition',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('개운하다', '개운하다'), ('머리가 아프다', '머리가 아프다'), ('눈이 아프거나 잘 안 떠진다', '눈이 아프거나 잘 안 떠진다'), ('몸이 결리거나 뻐근하다', '몸이 결리거나 뻐근하다'), ('일어나기 힘들다', '일어나기 힘들다'), ('멍하다', '멍하다'), ('손이나 발 등이 저리다', '손이나 발 등이 저리다'), ('부어있다 (얼굴, 손, 발 등)', '부어있다 (얼굴, 손, 발 등)')], max_length=85, null=True),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='wakeup_first_thing',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('개운하다', '찬물 혹은 찬음료를 마신다'), ('머리가 아프다', '뜨거운 물 혹은 차를 마신다'), ('눈이 아프거나 잘 안 떠진다', '가벼운 스트레칭'), ('몸이 결리거나 뻐근하다', '양치, 세수, 샤워'), ('일어나기 힘들다', '스마트폰'), ('멍하다', '잡지, 신문')], max_length=54, null=True),
        ),
    ]
