# Generated by Django 3.0.5 on 2020-04-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_auto_20200427_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistcover',
            name='later_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistcover',
            name='previous_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checklistquestion',
            name='elements',
            field=models.CharField(blank=True, choices=[('wood', 'Wood'), ('fire', 'Fire'), ('earth', 'Earth'), ('metal', 'Metal'), ('water', 'Water'), ('sanghwa', 'Sanghwa')], max_length=20),
        ),
    ]
