# Generated by Django 3.0.5 on 2020-05-24 11:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_auto_20200524_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitchecklist',
            name='bad_thing',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='good_thing',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='sleeping',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('스마트폰', '스마트폰'), ('TV시청', 'TV시청'), ('책, 잡지, 신문 등 읽기', '책, 잡지, 신문 등 읽기'), ('일기, 글쓰기', '일기, 글쓰기'), ('야식', '야식')], max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='sleeping_etc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
