# Generated by Django 3.1a1 on 2020-05-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_auto_20200531_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='만들어진 날'),
        ),
        migrations.AlterField(
            model_name='checklistanswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='업데이트된 날'),
        ),
        migrations.AlterField(
            model_name='checklistquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='만들어진 날'),
        ),
        migrations.AlterField(
            model_name='checklistquestion',
            name='element',
            field=models.CharField(blank=True, choices=[('ELEMENT_WOOD', '목'), ('ELEMENT_FIRE', '화'), ('ELEMENT_EARTH', '토'), ('ELEMENT_METAL', '금'), ('ELEMENT_WATER', '수'), ('ELEMENT_SANGHWA', '상화')], max_length=20),
        ),
        migrations.AlterField(
            model_name='checklistquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='업데이트된 날'),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='만들어진 날'),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='업데이트된 날'),
        ),
    ]
