# Generated by Django 3.0.5 on 2020-04-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_auto_20200428_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistquestion',
            old_name='elements',
            new_name='element',
        ),
    ]
