# Generated by Django 3.0.5 on 2020-05-24 11:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_auto_20200524_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitchecklist',
            name='before_sleeping',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('스마트폰', '스마트폰'), ('TV시청', 'TV시청'), ('책, 잡지, 신문 등 읽기', '책, 잡지, 신문 등 읽기'), ('일기, 글쓰기', '일기, 글쓰기'), ('야식', '야식')], max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='habitchecklist',
            name='before_sleeping_etc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='sleeping',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('머리를 대면 바로 잠든다', '머리를 대면 바로 잠든다'), ('한참을 뒤척이다 자야 한다', '한참을 뒤척이다 자야 한다'), ('새벽에 꼭 한 번(이상) 일어난다', '새벽에 꼭 한 번(이상) 일어난다'), ('잠을 못 잔다', '잠을 못 잔다')], max_length=55, null=True),
        ),
    ]
