# Generated by Django 3.0.5 on 2020-04-27 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklists', '0005_auto_20200427_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.CheckListQuestion'),
        ),
        migrations.AlterField(
            model_name='checklistcover',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkListCover', to=settings.AUTH_USER_MODEL),
        ),
    ]
