# Generated by Django 3.1a1 on 2020-05-31 05:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_auto_20200531_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistanswer',
            name='later_answer',
            field=models.BooleanField(default=False, verbose_name='답변 2'),
        ),
        migrations.AlterField(
            model_name='checklistanswer',
            name='previous_answer',
            field=models.BooleanField(default=False, verbose_name='답변 1'),
        ),
        migrations.AlterField(
            model_name='checklistanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_set', to='checklists.checklistquestion', verbose_name='질문'),
        ),
        migrations.AlterField(
            model_name='checklistanswer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='고유 번호'),
        ),
        migrations.AlterField(
            model_name='checklistquestion',
            name='element',
            field=models.CharField(blank=True, choices=[('ELEMENT_WOOD', '목'), ('ELEMENT_FIRE', '화'), ('ELEMENT_EARTH', '토'), ('ELEMENT_METAL', '금'), ('ELEMENT_WATER', '수'), ('ELEMENT_SANGHWA', '상화')], max_length=20, verbose_name='오행'),
        ),
        migrations.AlterField(
            model_name='checklistquestion',
            name='question',
            field=models.CharField(max_length=5000, verbose_name='질문'),
        ),
        migrations.AlterField(
            model_name='checklistquestion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='고유 번호'),
        ),
    ]
