# Generated by Django 3.0.5 on 2020-05-24 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklists', '0007_auto_20200524_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitchecklist',
            name='job',
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
