# Generated by Django 3.0.5 on 2020-05-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0008_auto_20200524_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitchecklist',
            name='meal_with_night_food',
            field=models.CharField(choices=[('DEGREE_A', '안한다'), ('DEGREE_B', '거의 안한다'), ('DEGREE_C', '가끔 한다'), ('DEGREE_D', '자주 한다'), ('DEGREE_E', '매일 한다')], default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='meal_with_snack',
            field=models.CharField(choices=[('DEGREE_A', '안한다'), ('DEGREE_B', '거의 안한다'), ('DEGREE_C', '가끔 한다'), ('DEGREE_D', '자주 한다'), ('DEGREE_E', '매일 한다')], default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='meal_with_water',
            field=models.CharField(choices=[('DEGREE_A', '안한다'), ('DEGREE_B', '거의 안한다'), ('DEGREE_C', '가끔 한다'), ('DEGREE_D', '자주 한다'), ('DEGREE_E', '매일 한다')], default=1, max_length=300),
            preserve_default=False,
        ),
    ]
