# Generated by Django 3.0.5 on 2020-05-25 15:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_auto_20200525_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitchecklist',
            name='meal',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitchecklist',
            name='wakeup_first_thing',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('WAKEUP_FIRST_THING_A', '찬물 혹은 찬음료를 마신다'), ('WAKEUP_FIRST_THING_B', '뜨거운 물 혹은 차를 마신다'), ('WAKEUP_FIRST_THING_C', '가벼운 스트레칭'), ('WAKEUP_FIRST_THING_D', '양치, 세수, 샤워'), ('WAKEUP_FIRST_THING_E', '스마트폰'), ('WAKEUP_FIRST_THING_F', '잡지, 신문')], max_length=125, null=True),
        ),
    ]
